dingus_fnc_SandboxAddCargo01 =
{
  params ["_boxes"];
  
  { clearItemCargo _x; clearWeaponCargo _x; clearMagazineCargo _x; clearBackpackCargo _x; } forEach _boxes;

  _boxes params ["_box0", "_box1", "_box2", "_box3", "_box4", "_box5", "_box6"];

  _box0 addItemCargo ["V_Rangemaster_belt", 10];
  _box0 addItemCargo ["V_BandollierB_khk", 10];
  _box0 addItemCargo ["V_BandollierB_cbr", 10];
  _box0 addItemCargo ["V_BandollierB_rgr", 10];
  _box0 addItemCargo ["V_BandollierB_blk", 10];
  _box0 addItemCargo ["V_BandollierB_oli", 10];
  _box0 addItemCargo ["V_PlateCarrier1_rgr", 10];
  _box0 addItemCargo ["V_PlateCarrier2_rgr", 10];
  _box0 addItemCargo ["V_PlateCarrier3_rgr", 10];
  _box0 addItemCargo ["V_PlateCarrierGL_rgr", 10];
  _box0 addItemCargo ["V_PlateCarrier1_blk", 10];
  _box0 addItemCargo ["V_PlateCarrierSpec_rgr", 10];
  _box0 addItemCargo ["V_Chestrig_khk", 10];
  _box0 addItemCargo ["V_Chestrig_rgr", 10];
  _box0 addItemCargo ["V_Chestrig_blk ", 10];
  _box0 addItemCargo ["V_Chestrig_oli ", 10];
  _box0 addItemCargo ["V_TacVest_khk", 10];
  _box0 addItemCargo ["V_TacVest_brn", 10];
  _box0 addItemCargo ["V_TacVest_oli", 10];
  _box0 addItemCargo ["V_TacVest_blk ", 10];
  _box0 addItemCargo ["V_TacVest_camo", 10];
  _box0 addItemCargo ["V_TacVest_blk_POLICE", 10];
  _box0 addItemCargo ["V_TacVestIR_blk", 10];
  _box0 addItemCargo ["V_TacVestCamo_khk", 10];
  _box0 addItemCargo ["V_HarnessO_brn", 10];
  _box0 addItemCargo ["V_HarnessOGL_brn", 10];
  _box0 addItemCargo ["V_HarnessO_gry", 10];
  _box0 addItemCargo ["V_HarnessOGL_gry", 10];
  _box0 addItemCargo ["V_HarnessOSpec_brn", 10];
  _box0 addItemCargo ["V_HarnessOSpec_gry", 10];
  _box0 addItemCargo ["V_PlateCarrierIA1_dgtl", 10];
  _box0 addItemCargo ["V_PlateCarrierIA2_dgtl", 10];
  _box0 addItemCargo ["V_PlateCarrierIAGL_dgtl", 10];
  _box0 addItemCargo ["V_RebreatherB", 10];
  _box0 addItemCargo ["V_RebreatherIR", 10];
  _box0 addItemCargo ["V_RebreatherIA", 10];
  _box0 addItemCargo ["V_PlateCarrier_Kerry", 10];
  _box0 addItemCargo ["V_PlateCarrierL_CTRG", 10];
  _box0 addItemCargo ["V_PlateCarrierH_CTRG", 10];
  _box0 addItemCargo ["V_I_G_resistanceLeader_F", 10];
  _box0 addItemCargo ["V_Press_F", 10];

  _box1 addItemCargo ["H_HelmetB ", 10];
  _box1 addItemCargo ["H_HelmetB_camo", 10];
  _box1 addItemCargo ["H_HelmetB_paint", 10];
  _box1 addItemCargo ["H_HelmetB_light", 10];
  _box1 addItemCargo ["H_Booniehat_khk", 10];
  _box1 addItemCargo ["H_Booniehat_oli", 10];
  _box1 addItemCargo ["H_Booniehat_indp", 10];
  _box1 addItemCargo ["H_Booniehat_mcamo", 10];
  _box1 addItemCargo ["H_Booniehat_grn", 10];
  _box1 addItemCargo ["H_Booniehat_tan", 10];
  _box1 addItemCargo ["H_Booniehat_dirty", 10];
  _box1 addItemCargo ["H_Booniehat_dgtl", 10];
  _box1 addItemCargo ["H_Booniehat_khk_hs", 10];
  _box1 addItemCargo ["H_HelmetB_plain_mcamo", 10];
  _box1 addItemCargo ["H_HelmetB_plain_blk", 10];
  _box1 addItemCargo ["H_HelmetSpecB", 10];
  _box1 addItemCargo ["H_HelmetSpecB_paint1", 10];
  _box1 addItemCargo ["H_HelmetSpecB_paint2", 10];
  _box1 addItemCargo ["H_HelmetSpecB_blk", 10];
  _box1 addItemCargo ["H_HelmetIA ", 10];
  _box1 addItemCargo ["H_HelmetIA_net", 10];
  _box1 addItemCargo ["H_HelmetIA_camo", 10];
  _box1 addItemCargo ["H_Helmet_Kerry", 10];
  _box1 addItemCargo ["H_HelmetB_grass", 10];
  _box1 addItemCargo ["H_HelmetB_snakeskin", 10];
  _box1 addItemCargo ["H_HelmetB_desert", 10];
  _box1 addItemCargo ["H_HelmetB_black", 10];
  _box1 addItemCargo ["H_HelmetB_sand", 10];
  _box1 addItemCargo ["H_Cap_red", 10];
  _box1 addItemCargo ["H_Cap_blu", 10];
  _box1 addItemCargo ["H_Cap_oli", 10];
  _box1 addItemCargo ["H_Cap_headphones", 10];
  _box1 addItemCargo ["H_Cap_tan", 10];
  _box1 addItemCargo ["H_Cap_blk", 10];
  _box1 addItemCargo ["H_Cap_blk_CMMG", 10];
  _box1 addItemCargo ["H_Cap_brn_SPECOPS", 10];
  _box1 addItemCargo ["H_Cap_tan_specops_US", 10];
  _box1 addItemCargo ["H_Cap_khaki_specops_UK", 10];
  _box1 addItemCargo ["H_Cap_grn", 10];
  _box1 addItemCargo ["H_Cap_grn_BI", 10];
  _box1 addItemCargo ["H_Cap_blk_Raven", 10];
  _box1 addItemCargo ["H_Cap_blk_ION", 10];
  _box1 addItemCargo ["H_Cap_oli_hs", 10];
  _box1 addItemCargo ["H_Cap_press", 10];
  _box1 addItemCargo ["H_Cap_usblack", 10];
  _box1 addItemCargo ["H_Cap_surfer", 10];
  _box1 addItemCargo ["H_Cap_police", 10];
  _box1 addItemCargo ["H_HelmetCrew_B", 10];
  _box1 addItemCargo ["H_HelmetCrew_O", 10];
  _box1 addItemCargo ["H_HelmetCrew_I", 10];
  _box1 addItemCargo ["H_PilotHelmetFighter_B", 10];
  _box1 addItemCargo ["H_PilotHelmetFighter_O", 10];
  _box1 addItemCargo ["H_PilotHelmetFighter_I", 10];
  _box1 addItemCargo ["H_PilotHelmetHeli_B", 10];
  _box1 addItemCargo ["H_PilotHelmetHeli_O", 10];
  _box1 addItemCargo ["H_PilotHelmetHeli_I", 10];
  _box1 addItemCargo ["H_CrewHelmetHeli_B", 10];
  _box1 addItemCargo ["H_CrewHelmetHeli_O", 10];
  _box1 addItemCargo ["H_CrewHelmetHeli_I", 10];
  _box1 addItemCargo ["H_HelmetO_ocamo", 10];
  _box1 addItemCargo ["H_HelmetLeaderO_ocamo", 10];
  _box1 addItemCargo ["H_MilCap_ocamo", 10];
  _box1 addItemCargo ["H_MilCap_mcamo", 10];
  _box1 addItemCargo ["H_MilCap_oucamo", 10];
  _box1 addItemCargo ["H_MilCap_rucamo", 10];
  _box1 addItemCargo ["H_MilCap_gry", 10];
  _box1 addItemCargo ["H_MilCap_dgtl", 10];
  _box1 addItemCargo ["H_MilCap_blue", 10];
  _box1 addItemCargo ["H_HelmetB_light_grass", 10];
  _box1 addItemCargo ["H_HelmetB_light_snakeskin", 10];
  _box1 addItemCargo ["H_HelmetB_light_desert", 10];
  _box1 addItemCargo ["H_HelmetB_light_black", 10];
  _box1 addItemCargo ["H_HelmetB_light_sand", 10];
  _box1 addItemCargo ["H_BandMask_blk", 10];
  _box1 addItemCargo ["H_BandMask_khk", 10];
  _box1 addItemCargo ["H_BandMask_reaper", 10];
  _box1 addItemCargo ["H_BandMask_demon", 10];
  _box1 addItemCargo ["H_HelmetO_oucamo", 10];
  _box1 addItemCargo ["H_HelmetLeaderO_oucamo", 10];
  _box1 addItemCargo ["H_HelmetSpecO_ocamo", 10];
  _box1 addItemCargo ["H_HelmetSpecO_blk", 10];
  _box1 addItemCargo ["H_Bandanna_surfer", 10];
  _box1 addItemCargo ["H_Bandanna_khk", 10];
  _box1 addItemCargo ["H_Bandanna_khk_hs", 10];
  _box1 addItemCargo ["H_Bandanna_cbr", 10];
  _box1 addItemCargo ["H_Bandanna_sgg", 10];
  _box1 addItemCargo ["H_Bandanna_sand", 10];
  _box1 addItemCargo ["H_Bandanna_surfer_blk", 10];
  _box1 addItemCargo ["H_Bandanna_surfer_grn", 10];
  _box1 addItemCargo ["H_Bandanna_gry", 10];
  _box1 addItemCargo ["H_Bandanna_blu", 10];
  _box1 addItemCargo ["H_Bandanna_camo", 10];
  _box1 addItemCargo ["H_Bandanna_mcamo", 10];
  _box1 addItemCargo ["H_Shemag_khk", 10];
  _box1 addItemCargo ["H_Shemag_tan", 10];
  _box1 addItemCargo ["H_Shemag_olive", 10];
  _box1 addItemCargo ["H_Shemag_olive_hs", 10];
  _box1 addItemCargo ["H_ShemagOpen_khk", 10];
  _box1 addItemCargo ["H_ShemagOpen_tan", 10];
  _box1 addItemCargo ["H_Beret_blk", 10];
  _box1 addItemCargo ["H_Beret_blk_POLICE", 10];
  _box1 addItemCargo ["H_Beret_red", 10];
  _box1 addItemCargo ["H_Beret_grn", 10];
  _box1 addItemCargo ["H_Beret_grn_SF", 10];
  _box1 addItemCargo ["H_Beret_brn_SF", 10];
  _box1 addItemCargo ["H_Beret_ocamo", 10];
  _box1 addItemCargo ["H_Beret_02", 10];
  _box1 addItemCargo ["H_Beret_Colonel", 10];
  _box1 addItemCargo ["H_Watchcap_blk", 10];
  _box1 addItemCargo ["H_Watchcap_cbr", 10];
  _box1 addItemCargo ["H_Watchcap_khk", 10];
  _box1 addItemCargo ["H_Watchcap_camo", 10];
  _box1 addItemCargo ["H_Watchcap_sgg", 10];
  _box1 addItemCargo ["H_TurbanO_blk", 10];
  _box1 addItemCargo ["H_StrawHat", 10];
  _box1 addItemCargo ["H_StrawHat_dark", 10];
  _box1 addItemCargo ["H_Hat_blue", 10];
  _box1 addItemCargo ["H_Hat_brown", 10];
  _box1 addItemCargo ["H_Hat_camo", 10];
  _box1 addItemCargo ["H_Hat_grey", 10];
  _box1 addItemCargo ["H_Hat_checker", 10];
  _box1 addItemCargo ["H_Hat_tan", 10];


  _box2 addItemCargo ["U_B_CombatUniform_mcam", 10];
  _box2 addItemCargo ["U_B_CombatUniform_mcam_tshirt", 10];
  _box2 addItemCargo ["U_B_CombatUniform_mcam_vest", 10];
  _box2 addItemCargo ["U_B_GhillieSuit", 10];
  _box2 addItemCargo ["U_B_HeliPilotCoveralls", 10];
  _box2 addItemCargo ["U_B_Wetsuit", 10];
  _box2 addItemCargo ["U_O_CombatUniform_ocamo", 10];
  _box2 addItemCargo ["U_O_GhillieSuit", 10];
  _box2 addItemCargo ["U_O_PilotCoveralls", 10];
  _box2 addItemCargo ["U_O_Wetsuit", 10];
  _box2 addItemCargo ["U_C_Poloshirt_blue", 10];
  _box2 addItemCargo ["U_C_Poloshirt_burgundy", 10];
  _box2 addItemCargo ["U_C_Poloshirt_stripped", 10];
  _box2 addItemCargo ["U_C_Poloshirt_tricolour", 10];
  _box2 addItemCargo ["U_C_Poloshirt_salmon", 10];
  _box2 addItemCargo ["U_C_Poloshirt_redwhite", 10];
  _box2 addItemCargo ["U_C_Commoner1_1", 10];
  _box2 addItemCargo ["U_C_Commoner1_2", 10];
  _box2 addItemCargo ["U_C_Commoner1_3", 10];
  _box2 addItemCargo ["U_Rangemaster", 10];
  _box2 addItemCargo ["U_NikosBody", 10];
  _box2 addItemCargo ["U_OrestesBody", 10];
  _box2 addItemCargo ["U_B_CombatUniform_mcam_worn", 10];
  _box2 addItemCargo ["U_B_SpecopsUniform_sgg", 10];
  _box2 addItemCargo ["U_B_PilotCoveralls", 10];
  _box2 addItemCargo ["U_O_CombatUniform_oucamo", 10];
  _box2 addItemCargo ["U_O_SpecopsUniform_ocamo", 10];
  _box2 addItemCargo ["U_O_SpecopsUniform_blk", 10];
  _box2 addItemCargo ["U_O_OfficerUniform_ocamo", 10];
  _box2 addItemCargo ["U_I_CombatUniform", 10];
  _box2 addItemCargo ["U_I_CombatUniform_tshirt", 10];
  _box2 addItemCargo ["U_I_CombatUniform_shortsleeve", 10];
  _box2 addItemCargo ["U_I_pilotCoveralls", 10];
  _box2 addItemCargo ["U_I_HeliPilotCoveralls", 10];
  _box2 addItemCargo ["U_I_GhillieSuit", 10];
  _box2 addItemCargo ["U_I_OfficerUniform", 10];
  _box2 addItemCargo ["U_I_Wetsuit", 10];
  _box2 addItemCargo ["U_Competitor", 10];
  _box2 addItemCargo ["U_MillerBody", 10];
  _box2 addItemCargo ["U_KerryBody", 10];
  _box2 addItemCargo ["U_IG_Guerilla1_1", 10];
  _box2 addItemCargo ["U_IG_Guerilla2_1", 10];
  _box2 addItemCargo ["U_IG_Guerilla2_2", 10];
  _box2 addItemCargo ["U_IG_Guerilla2_3", 10];
  _box2 addItemCargo ["U_IG_Guerilla3_1", 10];
  _box2 addItemCargo ["U_IG_Guerilla3_2", 10];
  _box2 addItemCargo ["U_IG_leader", 10];
  _box2 addItemCargo ["U_BG_Guerilla1_1", 10];
  _box2 addItemCargo ["U_BG_Guerilla2_1", 10];
  _box2 addItemCargo ["U_BG_Guerilla2_2", 10];
  _box2 addItemCargo ["U_BG_Guerilla2_3", 10];
  _box2 addItemCargo ["U_BG_Guerilla3_1", 10];
  _box2 addItemCargo ["U_BG_Guerilla3_2", 10];
  _box2 addItemCargo ["U_BG_leader", 10];
  _box2 addItemCargo ["U_OG_Guerilla1_1", 10];
  _box2 addItemCargo ["U_OG_Guerilla2_1", 10];
  _box2 addItemCargo ["U_OG_Guerilla2_2", 10];
  _box2 addItemCargo ["U_OG_Guerilla2_3", 10];
  _box2 addItemCargo ["U_OG_Guerilla3_1", 10];
  _box2 addItemCargo ["U_OG_Guerilla3_2", 10];
  _box2 addItemCargo ["U_OG_leader", 10];
  _box2 addItemCargo ["U_C_Poor_1", 10];
  _box2 addItemCargo ["U_C_Poor_2", 10];
  _box2 addItemCargo ["U_C_WorkerCoveralls", 10];
  _box2 addItemCargo ["U_C_Poor_shorts_1", 10];
  _box2 addItemCargo ["U_C_Commoner_shorts", 10];
  _box2 addItemCargo ["U_C_ShirtSurfer_shorts", 10];
  _box2 addItemCargo ["U_C_TeeSurfer_shorts_1", 10];
  _box2 addItemCargo ["U_C_TeeSurfer_shorts_2", 10];
  _box2 addItemCargo ["U_B_CTRG_1", 10];
  _box2 addItemCargo ["U_B_CTRG_2", 10];
  _box2 addItemCargo ["U_B_CTRG_3", 10];
  _box2 addItemCargo ["U_B_survival_uniform", 10];
  _box2 addItemCargo ["U_I_G_Story_Protagonist_F", 10];
  _box2 addItemCargo ["U_I_G_resistanceLeader_F", 10];
  _box2 addItemCargo ["U_C_Journalist", 10];
  _box2 addItemCargo ["U_C_Scientist", 10];
  _box2 addItemCargo ["U_NikosAgedBody", 10];
  _box2 addItemCargo ["U_Marshal", 10];
  _box2 addItemCargo ["U_B_Protagonist_VR", 10];
  _box2 addItemCargo ["U_O_Protagonist_VR", 10];
  _box2 addItemCargo ["U_I_Protagonist_VR", 10];
  _box2 addItemCargo ["U_IG_Guerrilla_6_1", 10];
  _box2 addItemCargo ["U_BG_Guerrilla_6_1", 10];
  _box2 addItemCargo ["U_OG_Guerrilla_6_1", 10];

  _box2 addItemCargo ["U_C_Driver_1", 10];
  _box2 addItemCargo ["U_C_Driver_2", 10];
  _box2 addItemCargo ["U_C_Driver_3", 10];
  _box2 addItemCargo ["U_C_Driver_4", 10];
  _box2 addItemCargo ["U_C_Driver_1_black", 10];
  _box2 addItemCargo ["U_C_Driver_1_blue", 10];
  _box2 addItemCargo ["U_C_Driver_1_green", 10];
  _box2 addItemCargo ["U_C_Driver_1_red", 10];
  _box2 addItemCargo ["U_C_Driver_1_white", 10];
  _box2 addItemCargo ["U_C_Driver_1_yellow", 10];
  _box2 addItemCargo ["U_C_Driver_1_orange", 10];


  _box3 addItemCargo ["muzzle_snds_H", 10];
  _box3 addItemCargo ["muzzle_snds_L", 10];
  _box3 addItemCargo ["muzzle_snds_M", 10];
  _box3 addItemCargo ["muzzle_snds_B", 10];
  _box3 addItemCargo ["muzzle_snds_H_MG", 10];
  _box3 addItemCargo ["muzzle_snds_H_SW", 10];
  _box3 addItemCargo ["muzzle_snds_acp", 10];
  _box3 addItemCargo ["muzzle_snds_338_black", 10];
  _box3 addItemCargo ["muzzle_snds_338_green", 10];
  _box3 addItemCargo ["muzzle_snds_338_sand", 10];
  _box3 addItemCargo ["muzzle_snds_93mmg", 10];
  _box3 addItemCargo ["muzzle_snds_93mmg_tan", 10];
  _box3 addItemCargo ["optic_Arco", 10];
  _box3 addItemCargo ["optic_Hamr", 10];
  _box3 addItemCargo ["optic_Aco", 10];
  _box3 addItemCargo ["optic_ACO_grn", 10];
  _box3 addItemCargo ["optic_Aco_smg", 10];
  _box3 addItemCargo ["optic_ACO_grn_smg", 10];
  _box3 addItemCargo ["optic_Holosight", 10];
  _box3 addItemCargo ["optic_Holosight_smg", 10];
  _box3 addItemCargo ["optic_SOS", 10];
  _box3 addItemCargo ["acc_flashlight", 10];
  _box3 addItemCargo ["acc_pointer_IR", 10];
  _box3 addItemCargo ["optic_MRCO", 10];
  _box3 addItemCargo ["optic_NVS", 10];
  _box3 addItemCargo ["optic_Nightstalker", 10];
  _box3 addItemCargo ["optic_tws", 10];
  _box3 addItemCargo ["optic_tws_mg", 10];
  _box3 addItemCargo ["optic_DMS", 10];
  _box3 addItemCargo ["optic_Yorris", 10];
  _box3 addItemCargo ["optic_MRD", 10];
  _box3 addItemCargo ["optic_LRPS", 10];
  _box3 addItemCargo ["optic_AMS", 10];
  _box3 addItemCargo ["optic_AMS_khk", 10];
  _box3 addItemCargo ["optic_AMS_snd", 10];
  _box3 addItemCargo ["optic_KHS_blk", 10];
  _box3 addItemCargo ["optic_KHS_hex", 10];
  _box3 addItemCargo ["optic_KHS_old", 10];
  _box3 addItemCargo ["optic_KHS_tan", 10];
  _box3 addItemCargo ["bipod_01_F_snd", 10];
  _box3 addItemCargo ["bipod_01_F_blk", 10];
  _box3 addItemCargo ["bipod_01_F_mtp", 10];
  _box3 addItemCargo ["bipod_02_F_blk", 10];
  _box3 addItemCargo ["bipod_02_F_tan", 10];
  _box3 addItemCargo ["bipod_02_F_hex", 10];
  _box3 addItemCargo ["bipod_03_F_blk", 10];
  _box3 addItemCargo ["bipod_03_F_oli", 10];

  _box4 addItemCargo ["HandGrenade_Stone", 18];
  _box4 addItemCargo ["HandGrenade", 18];
  _box4 addItemCargo ["MiniGrenade", 18];
  _box4 addItemCargo ["SmokeShell", 18];
  _box4 addItemCargo ["SmokeShellYellow", 18];
  _box4 addItemCargo ["SmokeShellGreen", 18];
  _box4 addItemCargo ["SmokeShellRed", 18];
  _box4 addItemCargo ["SmokeShellPurple", 18];
  _box4 addItemCargo ["SmokeShellOrange", 18];
  _box4 addItemCargo ["SmokeShellBlue", 18];
  _box4 addItemCargo ["Chemlight_green", 18];
  _box4 addItemCargo ["Chemlight_red", 18];
  _box4 addItemCargo ["Chemlight_yellow", 18];
  _box4 addItemCargo ["Chemlight_blue", 18];
  _box4 addItemCargo ["B_IR_Grenade", 18];
  _box4 addItemCargo ["O_IR_Grenade", 18];
  _box4 addItemCargo ["I_IR_Grenade", 18];

  _box5 addItemCargo ["ItemWatch", 10];
  _box5 addItemCargo ["ItemCompass", 10];
  _box5 addItemCargo ["ItemGPS", 10];
  _box5 addItemCargo ["ItemRadio", 10];
  _box5 addItemCargo ["ItemMap", 10];
  _box5 addItemCargo ["MineDetector", 10];
  _box5 addItemCargo ["FirstAidKit", 10];
  _box5 addItemCargo ["Medikit", 10];
  _box5 addItemCargo ["ToolKit", 10];
  _box5 addItemCargo ["Binocular", 10];
  _box5 addItemCargo ["Rangefinder", 10];
  _box5 addItemCargo ["NVGoggles", 10];
  _box5 addItemCargo ["NVGoggles_OPFOR", 10];
  _box5 addItemCargo ["NVGoggles_INDEP", 10];
  _box5 addItemCargo ["Laserdesignator", 10];
  _box5 addItemCargo ["Laserdesignator_02", 10];
  _box5 addItemCargo ["Laserdesignator_03", 10];
  _box5 addItemCargo ["B_UavTerminal", 10];
  _box5 addItemCargo ["O_UavTerminal", 10];
  _box5 addItemCargo ["I_UavTerminal", 10];
  _box5 addItemCargo ["Zasleh2", 10];

  _box6 addBackpackCargo ["B_AssaultPack_khk", 5];
  _box6 addBackpackCargo ["B_AssaultPack_dgtl", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr", 5];
  _box6 addBackpackCargo ["B_AssaultPack_sgg", 5];
  _box6 addBackpackCargo ["B_AssaultPack_blk", 5];
  _box6 addBackpackCargo ["B_AssaultPack_cbr", 5];
  _box6 addBackpackCargo ["B_AssaultPack_mcamo", 5];
  _box6 addBackpackCargo ["B_AssaultPack_ocamo", 5];
  _box6 addBackpackCargo ["B_Kitbag_rgr", 5];
  _box6 addBackpackCargo ["B_Kitbag_mcamo", 5];
  _box6 addBackpackCargo ["B_Kitbag_sgg", 5];
  _box6 addBackpackCargo ["B_Kitbag_cbr", 5];
  _box6 addBackpackCargo ["B_TacticalPack_rgr", 5];
  _box6 addBackpackCargo ["B_TacticalPack_mcamo", 5];
  _box6 addBackpackCargo ["B_TacticalPack_ocamo", 5];
  _box6 addBackpackCargo ["B_TacticalPack_blk", 5];
  _box6 addBackpackCargo ["B_TacticalPack_oli", 5];
  _box6 addBackpackCargo ["B_FieldPack_khk", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr", 5];
  _box6 addBackpackCargo ["B_FieldPack_blk", 5];
  _box6 addBackpackCargo ["B_Carryall_ocamo", 5];
  _box6 addBackpackCargo ["B_Carryall_oucamo", 5];
  _box6 addBackpackCargo ["B_Carryall_mcamo", 5];
  _box6 addBackpackCargo ["B_Carryall_khk", 5];
  _box6 addBackpackCargo ["B_Carryall_cbr", 5];
  _box6 addBackpackCargo ["B_Bergen_sgg", 5];
  _box6 addBackpackCargo ["B_Bergen_mcamo", 5];
  _box6 addBackpackCargo ["B_Bergen_rgr", 5];
  _box6 addBackpackCargo ["B_Bergen_blk", 5];
  _box6 addBackpackCargo ["B_OutdoorPack_blk", 5];
  _box6 addBackpackCargo ["B_OutdoorPack_tan", 5];
  _box6 addBackpackCargo ["B_OutdoorPack_blu", 5];
  _box6 addBackpackCargo ["B_HuntingBackpack", 5];
  _box6 addBackpackCargo ["B_AssaultPackG", 5];
  _box6 addBackpackCargo ["B_BergenG", 5];
  _box6 addBackpackCargo ["B_BergenC_red", 5];
  _box6 addBackpackCargo ["B_BergenC_grn", 5];
  _box6 addBackpackCargo ["B_BergenC_blu", 5];
  _box6 addBackpackCargo ["B_Parachute", 5];
  _box6 addBackpackCargo ["B_AssaultPack_khk", 5];
  _box6 addBackpackCargo ["B_AssaultPack_dgtl", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr", 5];
  _box6 addBackpackCargo ["B_AssaultPack_sgg", 5];
  _box6 addBackpackCargo ["B_AssaultPack_blk", 5];
  _box6 addBackpackCargo ["B_AssaultPack_cbr", 5];
  _box6 addBackpackCargo ["B_AssaultPack_mcamo", 5];
  _box6 addBackpackCargo ["B_AssaultPack_ocamo", 5];
  _box6 addBackpackCargo ["B_Kitbag_rgr", 5];
  _box6 addBackpackCargo ["B_Kitbag_mcamo", 5];
  _box6 addBackpackCargo ["B_Kitbag_sgg", 5];
  _box6 addBackpackCargo ["B_Kitbag_cbr", 5];
  _box6 addBackpackCargo ["B_TacticalPack_rgr", 5];
  _box6 addBackpackCargo ["B_TacticalPack_mcamo", 5];
  _box6 addBackpackCargo ["B_TacticalPack_ocamo", 5];
  _box6 addBackpackCargo ["B_TacticalPack_blk", 5];
  _box6 addBackpackCargo ["B_TacticalPack_oli", 5];
  _box6 addBackpackCargo ["B_FieldPack_khk", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr", 5];
  _box6 addBackpackCargo ["B_FieldPack_blk", 5];
  _box6 addBackpackCargo ["B_Carryall_ocamo", 5];
  _box6 addBackpackCargo ["B_Carryall_oucamo", 5];
  _box6 addBackpackCargo ["B_Carryall_mcamo", 5];
  _box6 addBackpackCargo ["B_Carryall_khk", 5];
  _box6 addBackpackCargo ["B_Carryall_cbr", 5];
  _box6 addBackpackCargo ["B_Bergen_sgg", 5];
  _box6 addBackpackCargo ["B_Bergen_mcamo", 5];
  _box6 addBackpackCargo ["B_Bergen_rgr", 5];
  _box6 addBackpackCargo ["B_Bergen_blk", 5];
  _box6 addBackpackCargo ["B_OutdoorPack_blk", 5];
  _box6 addBackpackCargo ["B_OutdoorPack_tan", 5];
  _box6 addBackpackCargo ["B_OutdoorPack_blu", 5];
  _box6 addBackpackCargo ["B_HuntingBackpack", 5];
  _box6 addBackpackCargo ["B_AssaultPackG", 5];
  _box6 addBackpackCargo ["B_BergenG", 5];
  _box6 addBackpackCargo ["B_BergenC_red", 5];
  _box6 addBackpackCargo ["B_BergenC_grn", 5];
  _box6 addBackpackCargo ["B_BergenC_blu", 5];
  _box6 addBackpackCargo ["B_Parachute", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr_LAT", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr_Medic", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr_Repair", 5];
  _box6 addBackpackCargo ["B_Assault_Diver", 5];
  _box6 addBackpackCargo ["B_AssaultPack_blk_DiverExp", 5];
  _box6 addBackpackCargo ["B_Kitbag_rgr_Exp", 5];
  _box6 addBackpackCargo ["B_FieldPack_blk_DiverExp", 5];
  _box6 addBackpackCargo ["O_Assault_Diver", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo_Medic", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_LAT", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_Repair", 5];
  _box6 addBackpackCargo ["B_Carryall_ocamo_Exp", 5];
  _box6 addBackpackCargo ["B_FieldPack_oli", 5];
  _box6 addBackpackCargo ["B_Carryall_oli", 5];
  _box6 addBackpackCargo ["G_AssaultPack", 5];
  _box6 addBackpackCargo ["G_Bergen", 5];
  _box6 addBackpackCargo ["C_Bergen_red", 5];
  _box6 addBackpackCargo ["C_Bergen_grn", 5];
  _box6 addBackpackCargo ["C_Bergen_blu", 5];
  _box6 addBackpackCargo ["B_AssaultPack_mcamo_AT", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr_ReconMedic", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr_ReconExp", 5];
  _box6 addBackpackCargo ["B_AssaultPack_rgr_ReconLAT", 5];
  _box6 addBackpackCargo ["B_AssaultPack_mcamo_AA", 5];
  _box6 addBackpackCargo ["B_AssaultPack_mcamo_AAR", 5];
  _box6 addBackpackCargo ["B_AssaultPack_mcamo_Ammo", 5];
  _box6 addBackpackCargo ["B_Kitbag_mcamo_Eng", 5];
  _box6 addBackpackCargo ["B_Carryall_mcamo_AAA", 5];
  _box6 addBackpackCargo ["B_Carryall_mcamo_AAT", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo_AA", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo_AAR", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo_ReconMedic", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_AT", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_AAT", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_AA", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_AAA", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_Medic", 5];
  _box6 addBackpackCargo ["B_FieldPack_ocamo_ReconExp", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_Ammo", 5];
  _box6 addBackpackCargo ["B_FieldPack_cbr_RPG_AT", 5];
  _box6 addBackpackCargo ["B_Carryall_ocamo_AAA", 5];
  _box6 addBackpackCargo ["B_Carryall_ocamo_Eng", 5];
  _box6 addBackpackCargo ["B_Carryall_cbr_AAT", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_AT", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_LAT", 5];
  _box6 addBackpackCargo ["B_Carryall_oucamo_AAT", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_AA", 5];
  _box6 addBackpackCargo ["B_Carryall_oucamo_AAA", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_AAR", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_Medic", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_Ammo", 5];
  _box6 addBackpackCargo ["B_FieldPack_oucamo_Repair", 5];
  _box6 addBackpackCargo ["B_Carryall_oucamo_Exp", 5];
  _box6 addBackpackCargo ["B_Carryall_oucamo_Eng", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_AA", 5];
  _box6 addBackpackCargo ["I_Assault_Diver", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_Ammo", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_Medic", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_Repair", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_LAT", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_AT", 5];
  _box6 addBackpackCargo ["I_Fieldpack_oli_AAR", 5];
  _box6 addBackpackCargo ["I_Carryall_oli_AAT", 5];
  _box6 addBackpackCargo ["I_Carryall_oli_Exp", 5];
  _box6 addBackpackCargo ["I_Carryall_oli_AAA", 5];
  _box6 addBackpackCargo ["I_Carryall_oli_Eng", 5];
  _box6 addBackpackCargo ["G_TacticalPack_Eng", 5];
  _box6 addBackpackCargo ["G_FieldPack_Medic", 5];
  _box6 addBackpackCargo ["G_FieldPack_LAT", 5];
  _box6 addBackpackCargo ["G_Carryall_Ammo", 5];
  _box6 addBackpackCargo ["G_Carryall_Exp", 5];

  
};

dingus_fnc_unitRemoveAllItemsAction = 
{
  _unit = _this select 0;
  removeAllWeapons _unit;
  removeAllItems _unit;
  removeAllAssignedItems _unit;
  removeUniform _unit;
  removeVest _unit;
  removeBackpack _unit;
  removeHeadgear _unit;
  removeGoggles _unit;
};

dingus_fnc_unitJoinGroupAction = 
{
  _unit = _this select 0;
  _grp = group player;
  [_unit] join _grp;

};

dingus_fnc_initUnits111 =
{
  comment "add action for the guys";
  params ["_units"];

  { _x addAction ["Remove all items", dingus_fnc_unitRemoveAllItemsAction]; } forEach _units;
};

dingus_fnc_initUnits222 =
{
  params ["_units"];

  { _x addAction ["Join Group", dingus_fnc_unitJoinGroupAction]; } forEach _units;
};

dingus_fnc_heloCmdFlyDefaultHeight = 
{
  _unit = _this select 0;
  _unit flyInHeight 75;
};

dingus_fnc_heloCmdFlyLowForEvac = 
{
  params ["_unit"];
  hint formatText ["%1", _unit];
  _unit flyInHeight 5;
};

dingus_fnc_heloCmdFlyFiveHundredMeters = 
{
  _unit = _this select 0;
  _unit flyInHeight 500;
};

dingus_fnc_heloCmdFlyJumpHeight = 
{
  _unit = _this select 0;
  _unit flyInHeight 1500;
};

dingus_fnc_testes = {
  hint "OK i'm here!";
};